name: Rust CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Check
      run: cargo check --verbose
      
    - name: Fmt
      run: cargo fmt --all --check
      continue-on-error: true
      
    - name: Clippy
      run: cargo clippy --workspace --all-targets --all-features -- -D warnings
      continue-on-error: true
      
    - name: Build
      run: cargo build --verbose
      
    - name: Run tests
      run: cargo test --verbose
